### PR TITLE
Build BeagleBone Getting Started app using grunt and nw.js

### PR DESCRIPTION
**Pull request by arianepaola**
Hello @jadonk

I have added a grunt script to build the BeagleBone Getting Started app using the latest nw.js release.
The script downloads automatically nw.js for each platform and builds the application.

To install the build dependencies, you can run npm in the main directory:
$ npm install --save-dev
If you do not have grunt installed, you can install it with
$ npm install grunt-cli --save-dev and run $ ./node_modules/.bin/grunt

Running grunt in the beaglebone-getting-started, containing the file Gruntfile.js, will build the application.

Thanks, Ariane

### CODE REVIEW

**Comment by jadonk** [comment]
Is my version of node/npm too old or something?

<pre>
timbird:beaglebone-getting-started jason$ npm install --save-dev
npm ERR! install Couldn't read dependencies
npm ERR! Error: no version
npm ERR!     at validVersion (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:579:32)
npm ERR!     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:341:23)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:140:33
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:334:40
npm ERR!     at fs.readFile (fs.js:176:14)
npm ERR!     at fs.close (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:5)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.5.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev"
npm ERR! cwd /Users/jason/workspace/beaglebone-getting-started
npm ERR! node -v v0.8.16
npm ERR! npm -v 1.1.69
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jason/workspace/beaglebone-getting-started/npm-debug.log
npm ERR! not ok code 0
</pre>

**Comment by arianepaola** [comment]
Hello @jadonk 

my npm is version 1.3.10~dfsg-1: all
Seems that it does not work with that npm version, is there a way for you to update it?

After running
beaglebone-getting-started$ npm install --save-dev

Please also make sure to install grunt-cli? (it does not work with --save-dev parameter, but still will install into the
node_modules directory)
beaglebone-getting-started$ npm install grunt-cli

Then I can run grunt:
beaglebone-getting-started$ ./node_modules/.bin/grunt 
Running "nodewebkit:src" (nodewebkit) task
Using v0.12.0
Create cache folder
...
...
Zipping README.htm
>> nodewebkit app created.

Done, without errors.

Hope this helps,

Ariane

**Comment by arianepaola** [comment]
Hello @jadonk 

Just tested it on Mac and it is working. Please try to update npm.
(Used node: v0.10.36 and npm: 1.4.28)

Build log is here: http://pastebin.com/HcGpB3BC

Thanks, Ariane

**Comment by jadonk** [comment]
The pull request still deletes a number of files not in the master branch. Can you please rebase against the master branch?

**Comment by jadonk** [comment]
Should this pull request be closed?

**Pull request merged**
